In [13]:
import pandas as pd

print ("seleccione el producto a comprar en nuestras opciones de 0 a 8")

menú={"Productos":["Combo1","Combo2","combo3","combo 4","Papas","Jugos Naturales","Cerveza","Agua","Gaseosas"],"Precios":[20000,25000,18000,24500,3000,7000,3500,4000,2500]}
pd.DataFrame.from_dict(menú)

seleccione el producto a comprar en nuestras opciones de 0 a 8

         Productos  Precios
0           Combo1    20000
1           Combo2    25000
2           combo3    18000
3          combo 4    24500
4            Papas     3000
5  Jugos Naturales     7000
6          Cerveza     3500
7             Agua     4000
8         Gaseosas     2500

In [39]:
def mostrar_menu(opciones):
    print('Seleccione una opción:')
    for clave in sorted(opciones):
        print(f' {clave}) {opciones[clave][0]}')

def menu_principal():
  opciones = {
    '1': ('Opción 1', Combo1),
    '2': ('Opción 2', Combo2),
    '3': ('Opción 3', Combo3),
    '4': ('Opción 4', Combo4),
    '5': ('Opción 5', Papas),
    '6': ('Opción 6',JugoNaturales),
    '7': ('Opción 7', Cerveza),
    '8': ('Opción 8', Agua),
    '9': ('Opción 9', Gaseosa),
    '10': ('Salir', salir)
  }

def leer_opcion(opciones):
    while (a :=input('Opción: ')) not in opciones:
        print('Opción incorrecta, vuelva a intentarlo.')
    return a


def ejecutar_opcion(opcion, opciones):
    opciones[opcion][1]()


def generar_menu(opciones, opcion_salida):
    opcion = None
    while opcion != opcion_salida:
        mostrar_menu(opciones)
        opcion = leer_opcion(opciones)
        ejecutar_opcion(opcion, opciones)
        print()



def Combo1():
    print('Has elegido la opción 1')
def Combo2():
    print('Has elegido la opción 2')
def Combo3():
    print('Has elegido la opción 3')
def Combo4():
    print('Has elegido la opción 4')
def Papas():
    print('Has elegido la opción 5')
def JugoNaturales():
    print('Has elegido la opción 6')
def Cerveza():
    print('Has elegido la opción 7')
def Agua():
    print('Has elegido la opción 8')
def Gaseosa():
    print('Has elegido la opción 9')
def salir():
    print('Saliendo')

if __name__ == '__main__':
    menu_principal()

SyntaxError: ignored